"""empty message

Revision ID: 5c2cab4fdbbb
Revises: 6ef03f90ceab
Create Date: 2024-06-05 10:53:46.831187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c2cab4fdbbb'
down_revision = '6ef03f90ceab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.drop_constraint('image_user_data_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user_data', ['user_data_id'], ['user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('image_user_data_id_fkey', 'user_data', ['user_data_id'], ['id'])

    # ### end Alembic commands ###
